In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("S2.csv")
print(df)

    Class  Subject  Marks Gender
0      10    Maths     98      M
1      10    Maths     68      M
2      10  Science     78      M
3      10  Science     89      F
4      10  Science     91      M
5      10    Maths     92      F
6      10      SST     93      M
7      10      SST     94      F
8      10  Science     95      M
9      12  Science     96      F
10     12  Science     96      M
11     12  Science     97      F
12     12      SST     99      F
13     12  Science     90      F
14     12  English     85      F
15     12  Science     88      F

In [6]:
df1=pd.read_csv("data.csv", encoding=laten1)

<class 'NameError'>: name 'laten1' is not defined

In [7]:
df = pd.read_csv("data.csv", encoding="latin1")
print(df.head())

   User_ID  Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
0  1002903  Sanskriti  P00125942      F     26-35   28               0
1  1000732     Kartik  P00110942      F     26-35   35               1
2  1001990      Bindu  P00118542      F     26-35   35               1
3  1001425     Sudevi  P00237842      M      0-17   16               0
4  1000588       Joni  P00057942      M     26-35   28               1

            State      Zone       Occupation Product_Category  Orders  \
0     Maharashtra   Western       Healthcare             Auto       1
1  Andhra Pradesh  Southern             Govt             Auto       3
2   Uttar Pradesh   Central       Automobile             Auto       3
3       Karnataka  Southern     Construction             Auto       2
4         Gujarat   Western  Food Processing             Auto       2

    Amount  Status  unnamed1
0  23952.0     NaN       NaN
1  23934.0     NaN       NaN
2  23924.0     NaN       NaN
3  23912.0     NaN       NaN
4  23877.0     NaN       NaN

In [113]:
student={
    "Rollno":[101,102,103,104,105],
    "Name":["Amit","Priya","Rahul","Sahaa","Karan"],
    "Age":[20,21,19,22,20],
    "City":["Delhi","Mumbai","Pune","Delhi","Jaipur"],
    "Marks":[85,90,78,88,76]
}
print(student)

{'Rollno': [101, 102, 103, 104, 105], 'Name': ['Amit', 'Priya', 'Rahul', 'Sahaa', 'Karan'], 'Age': [20, 21, 19, 22, 20], 'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Jaipur'], 'Marks': [85, 90, 78, 88, 76]}

In [114]:
df=pd.DataFrame(student)
df.head(5)

   Rollno   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78
3     104  Sahaa   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [10]:
df.tail(2)

   Rollno   Name  Age    City  Marks
3     104  Sahaa   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [11]:
df.shape

(5, 5)

In [12]:
df.describe()

           Rollno        Age     Marks
count    5.000000   5.000000   5.00000
mean   103.000000  20.400000  83.40000
std      1.581139   1.140175   6.14817
min    101.000000  19.000000  76.00000
25%    102.000000  20.000000  78.00000
50%    103.000000  20.000000  85.00000
75%    104.000000  21.000000  88.00000
max    105.000000  22.000000  90.00000

In [13]:
df.to_csv("students.csv", index=False)

print("CSV file saved as output.csv")

CSV file saved as output.csv

In [15]:
df=pd.read_csv("students.csv")
print(df)

   Rollno   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78
3     104  Sahaa   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [16]:
employee={
    "":[101,102,103,104,105],
    "Name":["Amit","Priya","Rahul","Sahaa","Karan"],
    "Age":[20,21,19,22,20],
    "City":["Delhi","Mumbai","Pune","Delhi","Jaipur"],
    "Marks":[85,90,78,88,76]
}
print(employee)

{'Rollno': [101, 102, 103, 104, 105], 'Name': ['Amit', 'Priya', 'Rahul', 'Sahaa', 'Karan'], 'Age': [20, 21, 19, 22, 20], 'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Jaipur'], 'Marks': [85, 90, 78, 88, 76]}

In [17]:
df=pd.DataFrame(employee)
df.head(5)

   Rollno   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78
3     104  Sahaa   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [32]:
import pandas as pd

df = pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})

In [33]:
df.head()

   ID    Name  Age     City  Marks Department  Salary
0   1   Aarav   19  Lucknow     85         CS   30000
1   2  Vivaan   20    Delhi     90         IT   32000
2   3  Aditya   21   Mumbai     78         CS   28000
3   4  Vihaan   22     Pune     88         IT   35000
4   5   Arjun   20   Kanpur     92         EC   40000

In [34]:
df.describe()

             ID        Age      Marks       Salary
count  20.00000  20.000000  20.000000     20.00000
mean   10.50000  20.950000  84.600000  33725.00000
std     5.91608   1.316894   6.029751   4446.98301
min     1.00000  19.000000  73.000000  27000.00000
25%     5.75000  20.000000  79.750000  30375.00000
50%    10.50000  21.000000  85.500000  32750.00000
75%    15.25000  22.000000  89.250000  36500.00000
max    20.00000  23.000000  95.000000  42000.00000

In [35]:
df.to_csv("emp.csv", index=False)

In [36]:
print(df)

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [38]:
df.describe()

             ID        Age      Marks       Salary
count  20.00000  20.000000  20.000000     20.00000
mean   10.50000  20.950000  84.600000  33725.00000
std     5.91608   1.316894   6.029751   4446.98301
min     1.00000  19.000000  73.000000  27000.00000
25%     5.75000  20.000000  79.750000  30375.00000
50%    10.50000  21.000000  85.500000  32750.00000
75%    15.25000  22.000000  89.250000  36500.00000
max    20.00000  23.000000  95.000000  42000.00000

In [39]:
print(df.loc[0])
print(df.iloc[0])

ID                  1
Name            Aarav
Age                19
City          Lucknow
Marks              85
Department         CS
Salary          30000
Name: 0, dtype: object
ID                  1
Name            Aarav
Age                19
City          Lucknow
Marks              85
Department         CS
Salary          30000
Name: 0, dtype: object

In [42]:
print(df.loc[0:5])

   ID     Name  Age     City  Marks Department  Salary
0   1    Aarav   19  Lucknow     85         CS   30000
1   2   Vivaan   20    Delhi     90         IT   32000
2   3   Aditya   21   Mumbai     78         CS   28000
3   4   Vihaan   22     Pune     88         IT   35000
4   5    Arjun   20   Kanpur     92         EC   40000
5   6  Reyansh   23    Noida     76         CS   27000

In [48]:
print(df.loc[1:10:2])

   ID     Name  Age    City  Marks Department  Salary
1   2   Vivaan   20   Delhi     90         IT   32000
3   4   Vihaan   22    Pune     88         IT   35000
5   6  Reyansh   23   Noida     76         CS   27000
7   8  Krishna   22  Jaipur     95         EC   42000
9  10    Kabir   20  Mumbai     84         IT   34000

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})

In [99]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya",None,"Karan","Priya","Rahul","Neha",None,
             "Vikas","Pooja","Ankit","Simran","Rohit",None,"Kajal",
             "Deepak","Meena","Arjun","Nisha",None],

    "Age": [20,21,np.nan,22,19,23,21,20,np.nan,22,
            24,23,21,20,22,np.nan,19,21,23,20],

    "City": ["Delhi","Mumbai","Pune",None,"Jaipur","Delhi","Mumbai",
             "Pune","Delhi",None,"Jaipur","Mumbai","Delhi","Pune",
             None,"Delhi","Mumbai","Jaipur","Pune","Delhi"],

    "Marks": [85,90,78,np.nan,88,76,91,82,95,np.nan,
              80,84,79,92,87,75,np.nan,89,81,93]
})

print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [79]:
df.to_csv("emp.csv", index=False)

In [80]:
df.head()

   Student_ID   Name   Age    City  Marks
0         101   Aman  20.0   Delhi   85.0
1         102   Riya  21.0  Mumbai   90.0
2         103   None   NaN    Pune   78.0
3         104  Karan  22.0    None    NaN
4         105  Priya  19.0  Jaipur   88.0

In [81]:
df.describe()

       Student_ID        Age     Marks
count    20.00000  17.000000  17.00000
mean    110.50000  21.235294  85.00000
std       5.91608   1.480262   6.22495
min     101.00000  19.000000  75.00000
25%     105.75000  20.000000  80.00000
50%     110.50000  21.000000  85.00000
75%     115.25000  22.000000  90.00000
max     120.00000  24.000000  95.00000

In [82]:
df.isnull().sum()

Student_ID    0
Name          4
Age           3
City          3
Marks         3
dtype: int64

In [83]:
print(df.dropna())

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [84]:
print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [85]:
df.dropna(inplace=True)

In [86]:
print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [87]:
df.describe()

       Student_ID        Age      Marks
count   10.000000  10.000000  10.000000
mean   109.400000  21.600000  84.300000
std      6.239658   1.577621   5.165054
min    101.000000  19.000000  76.000000
25%    105.250000  21.000000  80.250000
50%    109.000000  21.000000  84.500000
75%    112.750000  23.000000  88.750000
max    119.000000  24.000000  91.000000

In [94]:
print(df.isnull().sum())

Student_ID    0
Name          4
Age           3
City          3
Marks         3
dtype: int64

In [95]:
df.fillna(0)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103       0   0.0    Pune   78.0
3          104   Karan  22.0       0    0.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108       0  20.0    Pune   82.0
8          109   Vikas   0.0   Delhi   95.0
9          110   Pooja  22.0       0    0.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114       0  20.0    Pune   92.0
14         115   Kajal  22.0       0   87.0
15         116  Deepak   0.0   Delhi   75.0
16         117   Meena  19.0  Mumbai    0.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120       0  20.0   Delhi   93.0

In [100]:
df.fillna("Not available")

    Student_ID           Name            Age           City          Marks
0          101           Aman           20.0          Delhi           85.0
1          102           Riya           21.0         Mumbai           90.0
2          103  Not available  Not available           Pune           78.0
3          104          Karan           22.0  Not available  Not available
4          105          Priya           19.0         Jaipur           88.0
5          106          Rahul           23.0          Delhi           76.0
6          107           Neha           21.0         Mumbai           91.0
7          108  Not available           20.0           Pune           82.0
8          109          Vikas  Not available          Delhi           95.0
9          110          Pooja           22.0  Not available  Not available
10         111          Ankit           24.0         Jaipur           80.0
11         112         Simran           23.0         Mumbai           84.0
12         113          Rohit           21.0          Delhi           79.0
13         114  Not available           20.0           Pune           92.0
14         115          Kajal           22.0  Not available           87.0
15         116         Deepak  Not available          Delhi           75.0
16         117          Meena           19.0         Mumbai  Not available
17         118          Arjun           21.0         Jaipur           89.0
18         119          Nisha           23.0           Pune           81.0
19         120  Not available           20.0          Delhi           93.0

In [91]:
df.fillna({'Name': 'Not Available', 'Marks' : 0, 'Age' : 18})

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [112]:
df["City"].str.replace("Delhi","Lucknow")

0     Lucknow
1      Mumbai
2        Pune
3        None
4      Jaipur
5     Lucknow
6      Mumbai
7        Pune
8     Lucknow
9        None
10     Jaipur
11     Mumbai
12    Lucknow
13       Pune
14       None
15    Lucknow
16     Mumbai
17     Jaipur
18       Pune
19    Lucknow
Name: City, dtype: object